name: Release On Update

on: [push, pull_request]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate new tokens
        run: python3 utils/merge_token_list.py

      - uses: actions/upload-artifact@v4
        with:
          name: merged-coin-list
          path: |
            logo/
            merged_coins.json

      # - name: Create release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     files: merged_coins.json
      #     tag: latest
      #   env:
      #     GH_ENTERPRISE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
